### ISSUE TITLE
How can I check Buffer.isBuffer()?

### ISSUE THREAD

**Issue by junderw** [junderw/tiny-secp256k1-wasm#3]
Type checks are checking if a Buffer was passed and it is a certain length.

Perhaps I need to implement it in the JS glue code...

#2

**Comment by yuki-js** [comment]
`JsBuffer` is currently dummy type. Import Buffer object.
wasm-bindgen can duck-typing. 
https://rustwasm.github.io/docs/wasm-bindgen/reference/working-with-duck-typed-interfaces.html

**Comment by junderw** [comment]
This also is interesting:

https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/js_class.html

**Comment by junderw** [comment]
I was able to implement `Buffer::from` but `Buffer::is_buffer` requires ownership of the value passed in, and that adds a lot of copying.

**Comment by junderw** [comment]
I wonder if there's a way to create a new type besides JsBuffer that will perform checks when wasm-bindgen passes in the Box<[u8]>...

It feels like something rust would do well. I'll have to look into it.

**Comment by junderw** [comment]
```rust
impl From<Box<[u8]>> for MyType {
  pub fn from(bytes: Box<[u8]>) -> Self {
    // Buffer::is_Buffer(bytes) checks etc...

    // but does the From trait allow returning a Result?
    // checking the values when it is casted into the parameters etc...
  }
}
```

**Comment by yuki-js** [comment]
We would be better to make low-level wrapper.
But I am little worried because recipe without wasm-bindgen is few.

**Comment by junderw** [comment]
it is impossible to do isBuffer right now, since any Buffers passed in are converted to Uint8Array, so checking is moot.

This can only be fixed by a wrapper added on our end, or if wasm-bindgen adds some new functionality.
