### ISSUE TITLE
js_sys::Uint8Array::view is causing errors against the test vectors

### ISSUE THREAD

**Issue by junderw** [junderw/tiny-secp256k1-wasm#8]
I am running the test vectors from the main library against this and found a problem.

I need to return a Uint8Array OR null for some functions.

However, Box<[u8]> is replaced with Uint8Array, but JSValue is needed to return null...

How to fix this?...

example:

```rust
    #[wasm_bindgen(js_name = pointAdd)]
    pub fn point_add(
        &self,
        p_a: JsBuffer,
        p_b: JsBuffer,
        compressed: Option<bool>,
    ) -> Result<JsValue, JsValue> {
        let puba = PublicKey::from_slice(&p_a)
            .map_err(|_| JsValue::from(TypeError::new("Expected Point")))?;
        let pubb = PublicKey::from_slice(&p_b)
            .map_err(|_| JsValue::from(TypeError::new("Expected Point")))?;

        let key_option = match puba.combine(&pubb) {
            Ok(a) => Some(a),
            Err(_) => None,
        };

        if key_option == None {
            return Ok(JsValue::NULL);
        }

        let result = key_option.unwrap();

        let is_compressed = compressed.unwrap_or(p_a.len() == 33);

        if is_compressed {
            unsafe {
                let array = js_sys::Uint8Array::view(&mut result.serialize());
                return Ok(JsValue::from(array));
            }
        } else {
            unsafe {
                let array = js_sys::Uint8Array::view(&mut result.serialize_uncompressed());
                return Ok(JsValue::from(array));
            }
        }
    }
```

**Comment by junderw** [comment]
It seems like covering everything in `Buffer.from()` after getting the return value solved the problem...

Though I'm not sure why.

**Comment by junderw** [comment]
Added a simple wrapper for testing against tiny-secp256k1 test cases.

All tests are passing currently.

Not sure why this breaks the tests... perhaps rust is modifying memory in-place?

**Comment by junderw** [comment]
https://github.com/junderw/tiny-secp256k1-wasm/commit/921d5006369cc6470324d3235da0b3a892375238

**Comment by yuki-js** [comment]
JsValue impls `From<T: JsCast>` and `JsCast` needs `AsRef` and `[u8]` is `AsRef`, which means `[u8]` can be converted into reference, and reference can be converted into JsValue.
https://docs.rs/wasm-bindgen/0.2.63/wasm_bindgen/struct.JsValue.html#impl-From%3C%26%27a%20T%3E

This can convert `[u8]` to `Uint8Array`, not `Buffer`. Because `Buffer` is subclass of `Uint8Array`, it may not be a practical problem, but tests will fail.

**Comment by yuki-js** [comment]
To return truthy-value or null(perhaps undefined), 

```rust
- ) -> Result<JsValue, JsValue> {
+ ) -> Result<Option<SomeReturnType>, JsValue> {
```

type is auto-converted by bindgen with the mechanisms I mentioned above.

**Comment by junderw** [comment]
I was able to return Buffers properly and avoid this issue.
